// 明日方舟：終末地 角色資料
// 包含官方角色介紹與特性

const operatorsData = [
    {
        id: 1,
        name: "艾爾黛拉",
        cnName: "艾爾黛拉",
        enName: "Ardelia",
        rarity: 6,
        class: "Support",
        element: "Nature",
        weapon: "Arts Unit",
        faction: "羅德島",
        description: "她曾專注於火山研究，如今投身於超域與地質災害的現場勘查。她溫和又堅定，以探索為樂。艾爾黛拉的研究為終末地制定應對星球侵蝕的措施提供了重要依據。",
        trait: "地質研究專家｜治療、腐蝕、脆弱萬金油輔助",
        exclusiveWeapon: "滄溟星夢",
        mainStat: "智識提升",
        subStat: "治療效率提升",
        tags: ["治療", "輔助", "護盾"],
        icon: "Ardelia_icon.png",
        fullImage: "Ardelia_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "長息護手", "長息輔助臂", "長息輔助臂"] }
    },
    {
        id: 2,
        name: "餘燼",
        cnName: "餘燼",
        enName: "Ember",
        rarity: 6,
        class: "Defender",
        element: "Heat",
        weapon: "Greatsword",
        faction: "鐵誓軍",
        description: "請下令。餘燼是一位曾在北地生活的騎士，曾隸屬於一個叫作「鐵誓軍」的軍事組織。因自身堅持的「終極試煉」，餘燼來到了文明環帶遊歷，並受邀加入了終末地工業。",
        trait: "流浪騎士｜倒地和反擊一體的生存型角色",
        exclusiveWeapon: "大雷斑",
        mainStat: "力量提升",
        subStat: "生命提升",
        tags: ["防禦", "灼熱", "回復"],
        icon: "Ember_icon.png",
        fullImage: "Ember_Splash_Art.png",
        gearRecommendation: { setName: "點劍", pieces: ["點劍重裝甲", "點劍戰術手套", "輕超域穩定器", "點劍火石"] }
    },
    {
        id: 3,
        name: "管理員",
        cnName: "管理員",
        enName: "Endministrator",
        rarity: 6,
        class: "Guard",
        element: "Physical",
        weapon: "Sword",
        faction: "終末地工業",
        description: "在塔衛二成文記錄的歷史上，管理員是文明重要的保護者之一，曾多次在星球居民面臨重大災難時挺身而出，也因此留下了許多故事（以及傳說，乃至流言）。但真正的管理員本人仍是一個無比神秘的人物，很少有人親眼見過管理員。",
        trait: "神秘的管理者｜物理輸出與暴擊",
        exclusiveWeapon: "宏願",
        mainStat: "敏捷提升",
        subStat: "物理傷害提升",
        tags: ["輸出", "物理", "爆擊"],
        icon: "Endministrator_icon.png",
        fullImage: "Endadministrator_%28Female%29_Splash_Art.png",
        gearRecommendation: { setName: "點劍", pieces: ["點劍重裝甲", "輕超域護手", "點劍火石", "點劍火石"] }
    },
    {
        id: 4,
        name: "潔爾佩塔",
        cnName: "潔爾佩塔",
        enName: "Gilberta",
        rarity: 6,
        class: "Support",
        element: "Nature",
        weapon: "Arts Unit",
        faction: "羅德島",
        description: "管理員，你好呀！你身上有一股令人懷念的氣味……好像一封沒有寫完的信，我很好奇它會去往哪裡。潔爾佩塔來自羅德島製藥公司，以信使的身份為終末地工業提供服務。",
        trait: "開朗信使｜法術脆弱與聚怪輔助",
        exclusiveWeapon: "使命必達",
        mainStat: "意志提升",
        subStat: "終結技充能效率提升",
        tags: ["輔助", "治療", "增傷"],
        icon: "Gilberta_icon.png",
        fullImage: "Gilberta_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "長息護手", "長息輔助臂", "長息輔助臂"] }
    },
    {
        id: 5,
        name: "萊萬汀",
        cnName: "萊萬汀",
        enName: "Laevatain",
        rarity: 6,
        class: "Striker",
        element: "Heat",
        weapon: "Sword",
        faction: "羅德島",
        description: "破滅的黃昏！萊萬汀來自羅德島製藥公司，具備強大的獨立作戰能力。她雖然給人留下的第一印象通常是「火焰般的女孩」，但卻一点也不急躁，反而是個優秀的傾聽者和協調者。",
        trait: "火焰契約者｜灼熱爆發核心輸出",
        exclusiveWeapon: "熔鑄火焰",
        mainStat: "智識提升",
        subStat: "灼熱傷害提升",
        tags: ["輸出", "灼熱", "爆擊"],
        icon: "Laevatain_icon.png",
        fullImage: "Laevatain_Splash_Art.png",
        gearRecommendation: { setName: "動火用", pieces: ["落潮輕甲", "動火用手甲", "動火用測溫鏡", "動火用測溫鏡"] }
    },
    {
        id: 6,
        name: "別禮",
        cnName: "別禮",
        enName: "Last Rite",
        rarity: 6,
        class: "Striker",
        element: "Cryo",
        weapon: "Greatsword",
        faction: "終末地工業",
        description: "年輕的食腐者不願驚擾任何一人的死亡，拒絕本能對「進食」的呼喚，這讓她總是餓得昏天黑地，因為自卑而在人前畏畏縮縮。如今，她身著巫術時刻提供的作戰服，為了終末地的目標揮舞霜雪和兵刃。",
        trait: "冰劍師｜寒冷疊加與控制輸出",
        exclusiveWeapon: "赫拉芬格",
        mainStat: "力量提升",
        subStat: "寒冷傷害提升",
        tags: ["輸出", "寒冷", "控制"],
        icon: "Last_Rite_icon.png",
        fullImage: "Last_Rite_Splash_Art.png",
        gearRecommendation: { setName: "潮湧", pieces: ["拓荒護甲", "潮湧手甲", "懸河供氧栓", "懸河供氧栓"] }
    },
    {
        id: 7,
        name: "黎風",
        cnName: "黎風",
        enName: "Lifeng",
        rarity: 6,
        class: "Guard",
        element: "Physical",
        weapon: "Polearm",
        faction: "宏山",
        description: "武陵城見習衛兵隊員「黎風」，特來報到。黎風是武陵城衛兵隊預備役成員，在很小的时候，一场事故碾碎了他的一条手臂，也将他的父母带离了人世。接上義肢，認真走好每一步……",
        trait: "武陵城的少年｜物理脆弱與保護",
        exclusiveWeapon: "負山",
        mainStat: "敏捷提升",
        subStat: "物理傷害提升",
        tags: ["防禦", "輸出", "保護"],
        icon: "Lifeng_icon.png",
        fullImage: "Lifeng_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "長息護手", "點劍火石", "長息蓄電核"] }
    },
    {
        id: 8,
        name: "駿衛",
        cnName: "駿衛",
        enName: "Pogranichnik",
        rarity: 6,
        class: "Vanguard",
        element: "Physical",
        weapon: "Sword",
        faction: "終末地工業",
        description: "炎國邊境的警衛，常在前線奮戰。具備先手攻擊與迅速削減敵人的能力，能成為團隊的前排核心，穩定突破防線。",
        trait: "邊境警衛｜碎甲與團隊技力回復",
        exclusiveWeapon: "不知歸",
        mainStat: "意志提升",
        subStat: "攻擊提升",
        tags: ["先手", "輸出", "物理"],
        icon: "Pogranichnik_icon.png",
        fullImage: "Pogranichnik_Splash_Art.png",
        gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲叁型", "生物輔助手甲", "拓荒通信器", "拓荒通信器"] }
    },
    {
        id: 9,
        name: "秋栗",
        cnName: "秋栗",
        enName: "Akekuri",
        rarity: 4,
        class: "Vanguard",
        element: "Heat",
        weapon: "Sword",
        faction: "終末地工業",
        description: "Z7行動組，秋栗，很高興加入這次行動！請期待我的表現！秋栗作為年輕的商學院優等生，自薦加入終末地工業。她憑一己之力建立了Z7行動組，短短幾個月內完成了招募、訓練並投入實戰。",
        trait: "Z7組長｜灼熱附著、技力回復",
        exclusiveWeapon: "",
        mainStat: "敏捷提升",
        subStat: "灼熱傷害提升",
        tags: ["先手", "灼熱", "輸出"],
        icon: "Akekuri_icon.png",
        fullImage: "Akekuri_Splash_Art.png",
        gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲叁型", "長息護手", "拓荒增量供氧栓", "拓荒增量供氧栓"] }
    },
    {
        id: 10,
        name: "阿列什",
        cnName: "阿列什",
        enName: "Alesh",
        rarity: 5,
        class: "Guard",
        element: "Cryo",
        weapon: "Sword",
        faction: "終末地工業",
        description: "拋出去的竿隨時可以收回，人一旦陷入漩渦，就無法輕易脫身。阿列什，由前聯盟工團安全局聯絡人推薦加入終末地工業，在開拓區擔任聯絡與掩護工作。平日裡，他是個販鱗人，整日與釣竿為伴。",
        trait: "販鱗人｜寒冷附著與輔助控制",
        exclusiveWeapon: "",
        mainStat: "力量提升",
        subStat: "寒冷傷害提升",
        tags: ["輸出", "寒冷", "防禦"],
        icon: "Alesh_icon.png",
        fullImage: "Alesh_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["落潮輕甲", "長息護手", "拓荒增量供氧栓", "紓難印章"] }
    },
    {
        id: 11,
        name: "安塔爾",
        cnName: "安塔爾",
        enName: "Antal",
        rarity: 4,
        class: "Support",
        element: "Electric",
        weapon: "Arts Unit",
        faction: "終末地工業",
        description: "終末地Z7行動組成員，負責輔助與源石技術顧問的工作。頭腦聰明，思維跳躍，不擅於感知他人情緒，與人溝通時常常會作出和氣氛格格不入的發言，讓隊員們頗為頭痛。不過，在源石技藝上，安塔爾其實擁有著極為出眾的天賦，雖然對此他並無太多自覺。",
        trait: "Z7行動組｜法術脆弱、增幅",
        exclusiveWeapon: "",
        mainStat: "智識提升",
        subStat: "電磁傷害提升",
        tags: ["輸出", "雷電", "法術"],
        icon: "Antal_icon.png",
        fullImage: "Antal_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["落潮輕甲", "長息護手", "長息蓄電核", "長息蓄電核"] }
    },
    {
        id: 12,
        name: "弧光",
        cnName: "弧光",
        enName: "Arclight",
        rarity: 5,
        class: "Striker",
        element: "Electric",
        weapon: "Sword",
        faction: "眾生長地",
        description: "我叫伊庫特，代號是弧光，你好。我不會說什麼漂亮話，就祝你像漲水的河流一樣奔湧吧。弧光是一位眾生長地遊人，目前以技術顧問身份與終末地工業合作。",
        trait: "眾生長地遊人｜電擊穿透輸出",
        exclusiveWeapon: "",
        mainStat: "敏捷提升",
        subStat: "雷電傷害提升",
        tags: ["輸出", "雷電", "穿透"],
        icon: "Arclight_icon.png",
        fullImage: "Arclight_Splash_Art.png",
        gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲叁型", "50式應龍護手", "拓荒增量供氧栓", "拓荒增量供氧栓"] }
    },
    {
        id: 13,
        name: "艾維文娜",
        cnName: "艾維文娜",
        enName: "Avywenna",
        rarity: 5,
        class: "Support",
        element: "Electric",
        weapon: "Polearm",
        faction: "環塔商會",
        description: "你好呀，管理員，我就知道會在這裡找到你。有時候，可以稍微再依賴我一些哦。艾維文娜是一名武裝信使，曾在環塔商會工作，後來到了開拓區的荒野驛站。",
        trait: "武裝信使｜電擊脆弱與群傷收割",
        exclusiveWeapon: "向心之引",
        mainStat: "智識提升",
        subStat: "雷電傷害提升",
        tags: ["輸出", "雷電", "法術"],
        icon: "Avywenna_icon.png",
        fullImage: "Avywenna_Splash_Art.png",
        gearRecommendation: { setName: "碾骨", pieces: ["碾骨披巾", "50式應龍護手壹型", "碾骨小雕像", "碾骨小雕像"] }
    },
    {
        id: 14,
        name: "卡契爾",
        cnName: "卡契爾",
        enName: "Catcher",
        rarity: 4,
        class: "Defender",
        element: "Physical",
        weapon: "Greatsword",
        faction: "終末地工業",
        description: "需要掩護嗎？我會全力以赴的。終末地Z7行動組成員，負責掩護與後勤工作。卡契爾曾接受過完整的軍事訓練，大量的相關知識儲備讓他常能在關鍵時刻為隊友們提供合適的建議。幼年時因意外導致的病痛沒有將他擊垮，反而促使他逐漸成長為一名堅忍不拔的戰士。",
        trait: "Z7行動組｜庇護、護盾、虛弱",
        exclusiveWeapon: "",
        mainStat: "力量提升",
        subStat: "生命提升",
        tags: ["防禦", "保護", "物理"],
        icon: "Catcher_icon.png",
        fullImage: "Catcher_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "點劍戰術手套", "長息輔助臂", "長息輔助臂"] }
    },
    {
        id: 15,
        name: "啥子幹員(陳千語)",
        cnName: "陳千語",
        enName: "Chen Qianyu",
        rarity: 5,
        class: "Striker",
        element: "Physical",
        weapon: "Sword",
        faction: "終末地工業",
        description: "有時候太慎重了反倒容易誤事，所以說還是乾淨利落的打法更適合我啊……陳千語是終末地工業的特勤幹員。她自幼磨練武藝，刻苦訓練不僅讓她收獲了過硬的戰鬥素養，還練就了同年齡人中少有的心理素質。",
        trait: "陳家後裔｜物理輸出與先手",
        exclusiveWeapon: "仰止",
        mainStat: "敏捷提升",
        subStat: "物理傷害提升",
        tags: ["輸出", "物理", "先手"],
        icon: "Chen_Qianyu_icon.png",
        fullImage: "Chen_Qianyu_Splash_Art.png",
        gearRecommendation: { setName: "點劍", pieces: ["點劍重裝甲", "點劍戰術手套", "點劍火石", "點劍火石"] }
    },
    {
        id: 16,
        name: "大潘",
        cnName: "大潘",
        enName: "Da Pan",
        rarity: 5,
        class: "Defender",
        element: "Physical",
        weapon: "Greatsword",
        faction: "宏山",
        description: "謝謝，您有點高看我了。這麼的吧，有事儿您吩咐！大潘來自宏山科學院，在老家主要從事各項「離散型關鍵科研後勤支持工作」，也就是廚師、電工、木工、司機，職業練攤兒等等。",
        trait: "全能後勤｜反擊與防禦輸出",
        exclusiveWeapon: "",
        mainStat: "力量提升",
        subStat: "生命提升",
        tags: ["防禦", "保護", "生命力"],
        icon: "Da_Pan_icon.png",
        fullImage: "Da_Pan_Splash_Art.png",
        gearRecommendation: { setName: "輕超域", pieces: ["輕超域護板", "輕超域護手", "輕超域穩定器", "輕超域穩定器"] }
    },
    {
        id: 17,
        name: "埃特拉",
        cnName: "埃特拉",
        enName: "Estella",
        rarity: 4,
        class: "Guard",
        element: "Cryo",
        weapon: "Polearm",
        faction: "終末地工業",
        description: "呃……我感覺自己的身上正在承受整個世界的重擔……主要是膝蓋……終末地Z7行動組成員，負責情報收集和通信任務，體力很差。埃特拉總是被不幸所環繞，時不時會語出驚人。她因為自身感官的遲鈍反而有一些刺激性的愛好。理想是安穩地度過一生。",
        trait: "Z7行動組｜寒冷附著、擊飛、物理脆弱",
        exclusiveWeapon: "",
        mainStat: "敏捷提升",
        subStat: "寒冷傷害提升",
        tags: ["輸出", "寒冷", "反擊"],
        icon: "Estella_icon.png",
        fullImage: "Estella_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["碾骨披巾", "長息護手", "長息輔助臂", "長息輔助臂"] }
    },
    {
        id: 18,
        name: "螢石",
        cnName: "螢石",
        enName: "Fluorite",
        rarity: 4,
        class: "Caster",
        element: "Nature",
        weapon: "Handcannon",
        faction: "終末地工業",
        description: "擾亂？牽制？還是……一步到位？終末地Z7行動組成員，負責偵察和戰線擾亂工作。螢石來自文明環帶邊緣的開拓區，在一次又一次遷移和流浪中鍛煉出了與眾不同的觀察力。比起手中雙銓，她如同讀心一般的敏銳感知和惡劣的性格才是最大的麻煩來源。",
        trait: "Z7行動組｜自然附著、減速",
        exclusiveWeapon: "",
        mainStat: "智識提升",
        subStat: "自然傷害提升",
        tags: ["輸出", "自然", "控制"],
        icon: "Fluorite_icon.png",
        fullImage: "Fluorite_Splash_Art.png",
        gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲叁型", "長息護手", "拓荒增量供氧栓", "拓荒增量供氧栓"] }
    },
    {
        id: 19,
        name: "佩麗卡",
        cnName: "佩麗卡",
        enName: "Perlica",
        rarity: 5,
        class: "Support",
        element: "Electric",
        weapon: "Arts Unit",
        faction: "終末地工業",
        description: "我曾經遙望著你的背影，而如今，我想和你並肩戰鬥。佩麗卡，終末地工業的監督和官方發言人，同時負責管理和推進協議技術的開發和應用，也承擔帝江號的日常管理工作。",
        trait: "終末地監督｜導電與電擊治療輔助",
        exclusiveWeapon: "",
        mainStat: "意志提升",
        subStat: "治療效率提升",
        tags: ["輔助", "治療", "雷電"],
        icon: "Perlica_icon.png",
        fullImage: "Perlica_Splash_Art.png",
        gearRecommendation: { setName: "脈衝式", pieces: ["脈衝式干擾服", "脈衝式手套", "脈衝式校準器", "脈衝式校準器"] }
    },
    {
        id: 20,
        name: "晝雪",
        cnName: "晝雪",
        enName: "Snowshine",
        rarity: 5,
        class: "Support",
        element: "Cryo",
        weapon: "Greatsword",
        faction: "羅德島",
        description: "我從不畏懼嚴寒和風雪！我願成為大家的堅盾！晝雪來自羅德島製藥公司，以救援專家的身份為終末地工業提供服務。",
        trait: "救援專家｜寒冷治療與防禦輔助",
        exclusiveWeapon: "",
        mainStat: "意志提升",
        subStat: "寒冷傷害提升",
        tags: ["輔助", "治療", "寒冷"],
        icon: "Snowshine_icon.png",
        fullImage: "Snowshine_Splash_Art.png",
        gearRecommendation: { setName: "生物輔助", pieces: ["生物輔助胸甲", "生物輔助手甲", "生物輔助護盾針", "生物輔助護盾針"] }
    },
    {
        id: 21,
        name: "狼衛",
        cnName: "狼衛",
        enName: "Wulfgard",
        rarity: 5,
        class: "Striker",
        element: "Heat",
        weapon: "Handcannon",
        faction: "終末地工業",
        description: "我知道力量並不代表一切，但在塔衛二，沒有力量通常不是什麼好事。一名生活在文明邊緣的裂地者傭兵。年輕的狼衛早已領教過人性中最黑暗的部分，但這并未消磨他的理智，反而砥礪出了他遠超年齡的成熟。",
        trait: "裂地者傭兵｜灼熱附著與範圍輸出",
        exclusiveWeapon: "同類相食",
        mainStat: "力量提升",
        subStat: "灼熱傷害提升",
        tags: ["輸出", "灼熱", "範圍"],
        icon: "Wulfgard_icon.png",
        fullImage: "Wulfgard_Splash_Art.png",
        gearRecommendation: { setName: "動火用", pieces: ["動火用外骨骼", "M.I.警用手套", "動火用測溫鏡", "動火用測溫鏡"] }
    },
    {
        id: 22,
        name: "賽希",
        cnName: "賽希",
        enName: "Xaihi",
        rarity: 5,
        class: "Caster",
        element: "Cryo",
        weapon: "Arts Unit",
        faction: "寂語修會",
        description: "我們共用知識與命運。初次見到賽希的人，往往很難第一時間判斷出她究竟來自何處。但賽希身上偶爾展現出的「拉特蘭風情」，卻能讓大家迅速意識到她一定來自寂語修會。",
        trait: "寂語修會成員｜寒冷附著與法術增幅輔助",
        exclusiveWeapon: "",
        mainStat: "智識提升",
        subStat: "寒冷傷害提升",
        tags: ["輸出", "寒冷", "控制"],
        icon: "Xaihi_icon.png",
        fullImage: "Xaihi_Splash_Art.png",
        gearRecommendation: { setName: "長息", pieces: ["落潮輕甲", "長息護手", "拓荒增量供氧栓", "拓荒增量供氧栓"] }
    },
    {
        id: 23,
        name: "伊馮",
        cnName: "伊馮",
        enName: "Yvonne",
        rarity: 6,
        class: "Striker",
        element: "Cryo",
        weapon: "Handcannon",
        faction: "終末地工業",
        description: "超域……一片未知而危險的世界，但未知總是讓人感到興奮，不是嗎？伊馮是終末地工業特種技術部門的研究員。她就像是一位自由不羈的時尚少女，但她是絕對的天才。",
        trait: "天才研究員｜凍結與暴擊輸出",
        exclusiveWeapon: "藝術暴君",
        mainStat: "智識提升",
        subStat: "暴擊率提升",
        tags: ["輸出", "寒冷", "爆擊"],
        icon: "Yvonne_icon.png",
        fullImage: "Yvonne_Splash_Art.png",
        gearRecommendation: { setName: "M.I.警用", pieces: ["M.I.警用罩衣", "M.I.警用手套", "M.I.警用工具組", "M.I.警用工具組"] }
    }
];

window.operatorsData = operatorsData;

// 導出數據
if (typeof module !== 'undefined' && module.exports) {
    module.exports = operatorsData;
}
