/**
 * 角色數據
 */

const operatorsData = [
    { id: 1, name: "艾爾黛拉", rarity: 6, class: "Support", element: "Nature", weapon: "Arts Unit", exclusiveWeapon: "滄溟星夢", mainStat: "智識提升", subStat: "治療效率提升", tags: ["治療", "輔助", "護盾"], icon: "Ardelia_icon.png", fullImage: "Ardelia_Splash_Art.png", description: "在末日社區長大的支援專家，專注於群體治療與護盾管理，能在團隊血量最低時提供關鍵救援，讓隊友在長時間戰鬥中持續存活與穩定輸出。", gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "長息護手", "長息輔助臂", "長息輔助臂"] } },
    { id: 2, name: "餘燼", rarity: 6, class: "Defender", element: "Heat", weapon: "Greatsword", exclusiveWeapon: "大雷斑", mainStat: "力量提升", subStat: "生命提升", tags: ["防禦", "灼熱", "回復"], icon: "Ember_icon.png", fullImage: "Ember_Splash_Art.png", description: "在灼熱戰場長大的防禦者，能以堅實護甲與強力反擊守護隊友。致力於讓團隊在長時間戰鬥中維持高生存與穩定輸出。", gearRecommendation: { setName: "生物輔助", pieces: ["生物輔助胸甲", "生物輔助手甲", "生物輔助護盾", "輕超域護板"] } },
    { id: 3, name: "管理員", rarity: 6, class: "Guard", element: "Physical", weapon: "Sword", exclusiveWeapon: "宏願", mainStat: "敏捷提升", subStat: "物理傷害提升", tags: ["輸出", "物理", "爆擊"], icon: "Endministrator_icon.png", fullImage: "Endadministrator_%28Female%29_Splash_Art.png", description: "謎一般的存在，過去曾與『天火』並肩作戰。擅長物理輸出與暴擊，能在戰場上給予敵人致命一擊，經驗豐富，善於判斷戰機與瞬間爆發。", gearRecommendation: { setName: "點劍", pieces: ["點劍重裝甲", "點劍戰術手套", "點劍火石", "碾骨面具"] } },
    { id: 4, name: "潔爾佩塔", rarity: 6, class: "Support", element: "Nature", weapon: "Arts Unit", exclusiveWeapon: "使命必達", mainStat: "意志提升", subStat: "終結技充能效率提升", tags: ["輔助", "治療", "增傷"], icon: "Gilberta_icon.png", fullImage: "Gilberta_Splash_Art.png", description: "在後勤崗位以坦薄蛋般的耐心支援整個團隊。專長於改善隊友續航與輸出節奏，讓每一次治療與增傷都落在需要的時刻。", gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "長息護手壹型", "長息輔助臂", "M.I.警用刺刃"] } },
    { id: 5, name: "萊萬汀", rarity: 6, class: "Striker", element: "Heat", weapon: "Sword", exclusiveWeapon: "熔鑄火焰", mainStat: "智識提升", subStat: "灼熱傷害提升", tags: ["輸出", "灼熱", "爆擊"], icon: "Laevatain_icon.png", fullImage: "Laevatain_Splash_Art.png", description: "炎之地的火焰契約者。脾氣火爆卻忠誠，灼熱傷害與暴擊率的結合讓他成為團隊的核心輸出，喜歡在近距離爆發。", gearRecommendation: { setName: "動火用", pieces: ["落潮輕甲", "動火用手甲", "動火用測溫鏡", "動火用測溫鏡"] } },
    { id: 6, name: "別禮", rarity: 6, class: "Striker", element: "Cryo", weapon: "Greatsword", exclusiveWeapon: "赫拉芬格", mainStat: "力量提升", subStat: "寒冷傷害提升", tags: ["輸出", "寒冷", "控制"], icon: "Last_Rite_icon.png", fullImage: "Last_Rite_Splash_Art.png", description: "冰雪劍師，過去與深淵有過交集，擁有強力寒冷輸出與控場能力，能讓敵人動作變慢並為隊友創造反擊窗口。", gearRecommendation: { setName: "潮湧", pieces: ["50式應龍輕甲", "潮湧手甲", "懸河供氧栓", "懸河供氧栓"] } },
    { id: 7, name: "黎風", rarity: 6, class: "Guard", element: "Physical", weapon: "Polearm", exclusiveWeapon: "負山", mainStat: "敏捷提升", subStat: "物理傷害提升", tags: ["防禦", "輸出", "保護"], icon: "Lifeng_icon.png", fullImage: "Lifeng_Splash_Art.png", description: "北方森林的守護者，靈活而堅韌。以長柄武器在前線壓制敵人，同時守護隊友的安危，讓戰場更穩定。", gearRecommendation: { setName: "碾骨", pieces: ["碾骨重護甲壹型", "點劍戰術手套", "碾骨面具", "碾骨面具"] } },
    { id: 8, name: "駿衛", rarity: 6, class: "Vanguard", element: "Physical", weapon: "Sword", exclusiveWeapon: "不知歸", mainStat: "意志提升", subStat: "攻擊提升", tags: ["先手", "輸出", "物理"], icon: "Pogranichnik_icon.png", fullImage: "Pogranichnik_Splash_Art.png", description: "炎國邊境的警衛，常在前線奮戰。具備先手攻擊與迅速削減敵人的能力，能成為團隊的前排核心，穩定突破防線。", gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲叁型", "生物輔助手甲", "拓荒通信器", "拓荒通信器"] } },
    { id: 9, name: "秋栗", rarity: 4, class: "Vanguard", element: "Heat", weapon: "Sword", exclusiveWeapon: "", mainStat: "敏捷提升", subStat: "灼熱傷害提升", tags: ["先手", "灼熱", "輸出"], icon: "Akekuri_icon.png", fullImage: "Akekuri_Splash_Art.png", description: "活潑開朗的炎國少女，熱衷於冒險與戰鬥。灼熱傷害搭配先手能力，能在戰鬥初期取得優勢，並以快速的機動性持續施壓。", gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲", "輕超域護手", "拓荒通信器", "拓荒通信器"] } },
    { id: 10, name: "阿列什", rarity: 5, class: "Guard", element: "Cryo", weapon: "Sword", exclusiveWeapon: "", mainStat: "力量提升", subStat: "寒冷傷害提升", tags: ["輸出", "寒冷", "防禦"], icon: "Alesh_icon.png", fullImage: "Alesh_Splash_Art.png", description: "謝拉格出身的寒冰劍士，性格冷靜沉著。結合防禦與輸出能力，寒冷傷害能有效克制敵人，並在隊伍中提供穩定的控場。", gearRecommendation: { setName: "蝕電絕緣", pieces: ["蝕電絕緣背心", "蝕電絕緣手套", "蝕電絕緣手套", "蝕電絕緣扳手"] } },
    { id: 11, name: "安塔爾", rarity: 4, class: "Caster", element: "Electric", weapon: "Arts Unit", exclusiveWeapon: "", mainStat: "智識提升", subStat: "電磁傷害提升", tags: ["輸出", "雷電", "法術"], icon: "Antal_icon.png", fullImage: "Antal_Splash_Art.png", description: "熱情的卡西米亞術師，專精於雷電法術。輸出型法師，电磁傷害能夠貫穿敵人防禦。", gearRecommendation: { setName: "長息", pieces: ["落潮輕甲", "輕超域護手", "輕超域護板", "輕超域護板"] } },
    { id: 12, name: "弧光", rarity: 5, class: "Striker", element: "Electric", weapon: "Sword", exclusiveWeapon: "", mainStat: "敏捷提升", subStat: "雷電傷害提升", tags: ["輸出", "雷電", "穿透"], icon: "Arclight_icon.png", fullImage: "Arclight_Splash_Art.png", description: "電閃雷鳴般的雷電劍士，速度與輸出兼具。雷電傷害具穿透特性，能在戰場中快速擊倒多名敵人。", gearRecommendation: { setName: "拓荒", pieces: ["拓荒護甲貳型", "50式應龍護手", "拓荒通信器", "拓荒通信器"] } },
    { id: 13, name: "艾維文娜", rarity: 5, class: "Caster", element: "Electric", weapon: "Polearm", exclusiveWeapon: "", mainStat: "智識提升", subStat: "雷電傷害提升", tags: ["輸出", "雷電", "法術"], icon: "Avywenna_icon.png", fullImage: "Avywenna_Splash_Art.png", description: "雷姆必拓的長柄法術使用者，擅長遠距離雷電輸出，控場與群體傷害並存，是隊伍法術輸出的核心。", gearRecommendation: { setName: "碾骨", pieces: ["碾骨披巾", "50式應龍護手壹型", "碾骨小雕像", "碾骨小雕像"] } },
    { id: 14, name: "卡契爾", rarity: 4, class: "Defender", element: "Physical", weapon: "Greatsword", exclusiveWeapon: "", mainStat: "力量提升", subStat: "生命提升", tags: ["防禦", "保護", "物理"], icon: "Catcher_icon.png", fullImage: "Catcher_Splash_Art.png", description: "沉默寡言的防禦型戰士，擅於保護隊友。具備高生命力與堅固防禦，是團隊的前線防護核心。", gearRecommendation: { setName: "重裝信使", pieces: ["重裝信使夾克", "重裝信使手套", "重裝信使陀螺", "重裝信使陀螺儀"] } },
    { id: 15, name: "啥子幹員", rarity: 5, class: "Striker", element: "Physical", weapon: "Sword", exclusiveWeapon: "仰止", mainStat: "敏捷提升", subStat: "物理傷害提升", tags: ["輸出", "物理", "先手"], icon: "Chen_Qianyu_icon.png", fullImage: "Chen_Qianyu_Splash_Art.png", description: "炎國陳家後裔，劍術出眾的年輕天才。以物理輸出與先手能力著稱，是隊伍中極具潛力的新星，值得長期培養。", gearRecommendation: { setName: "點劍", pieces: ["點劍重裝甲", "點劍戰術手套", "點劍火石", "碾骨面具"] } },
    { id: 16, name: "大潘", rarity: 5, class: "Defender", element: "Physical", weapon: "Greatsword", exclusiveWeapon: "", mainStat: "力量提升", subStat: "生命提升", tags: ["防禦", "保護", "生命力"], icon: "Da_Pan_icon.png", fullImage: "Da_Pan_Splash_Art.png", description: "性格溫和、內斂的防禦者，擁有卓越的生命力與穩健防禦，是隊伍的堅實後盾，能在壓力時承受傷害並保護隊友。", gearRecommendation: { setName: "輕超域", pieces: ["集成化重甲", "點劍戰術手套", "集成化陶瓷板", "集成化陶瓷板"] } },
    { id: 17, name: "埃特拉", rarity: 4, class: "Guard", element: "Cryo", weapon: "Polearm", exclusiveWeapon: "", mainStat: "敏捷提升", subStat: "寒冷傷害提升", tags: ["輸出", "寒冷", "反擊"], icon: "Estella_icon.png", fullImage: "Estella_Splash_Art.png", description: "謝拉格貴族出身的冰雪守衛，具備穩定的輸出與反擊能力，能以寒冷傷害慢下敵人速度，為隊友創造進攻窗口。", gearRecommendation: { setName: "50式應龍", pieces: ["50式應龍輕甲", "點劍戰術手套", "50式應龍雷達", "50式應龍雷達"] } },
    { id: 18, name: "螢石", rarity: 4, class: "Caster", element: "Nature", weapon: "Handcannon", exclusiveWeapon: "", mainStat: "智識提升", subStat: "自然傷害提升", tags: ["輸出", "自然", "控制"], icon: "Fluorite_icon.png", fullImage: "Fluorite_Splash_Art.png", description: "活潑開朗的自然系術師，擅長自然法術。手砲型法師，自然傷害具控場能力，能穩定控場並提供穩定輸出。", gearRecommendation: { setName: "M.I.警用", pieces: ["M.I.警用罩衣壹型", "M.I.警用手套", "M.I.警用工具組", "M.I.警用工具組"] } },
    { id: 19, name: "佩麗卡", rarity: 5, class: "Support", element: "Electric", weapon: "Arts Unit", exclusiveWeapon: "", mainStat: "意志提升", subStat: "治療效率提升", tags: ["輔助", "治療", "雷電"], icon: "Perlica_icon.png", fullImage: "Perlica_Splash_Art.png", description: "雷姆必拓的雷電治療專家，專長於穩定的隊伍回復。能在長時間戰鬥中持續恢復隊友生命值，並提供穩定的增益效果。", gearRecommendation: { setName: "脈衝式", pieces: ["脈衝式干擾服", "脈衝式手套", "脈衝式校準器", "脈衝式校準器"] } },
    { id: 20, name: "晝雪", rarity: 5, class: "Support", element: "Cryo", weapon: "Greatsword", exclusiveWeapon: "", mainStat: "意志提升", subStat: "寒冷傷害提升", tags: ["輔助", "治療", "寒冷"], icon: "Snowshine_icon.png", fullImage: "Snowshine_Splash_Art.png", description: "謝拉格雪域的溫柔醫療兵，專長於治療與寒冷輸出並存，能在團隊中提供穩定的支援與保護。", gearRecommendation: { setName: "生物輔助", pieces: ["生物輔助胸甲", "生物輔助手甲", "生物輔助護盾", "生物輔助護盾"] } },
    { id: 21, name: "狼衛", rarity: 5, class: "Striker", element: "Heat", weapon: "Handcannon", exclusiveWeapon: "同類相食", mainStat: "力量提升", subStat: "灼熱傷害提升", tags: ["輸出", "灼熱", "範圍"], icon: "Wulfgard_icon.png", fullImage: "Wulfgard_Splash_Art.png", description: "炎國北方部落的戰士，專長近距離灼熱輸出與範圍攻擊。以高傷害與穩定輸出著稱，能在團隊前線造成壓力。", gearRecommendation: { setName: "動火用", pieces: ["動火用外骨骼", "M.I.警用手套", "動火用測溫鏡", "動火用測溫鏡"] } },
    { id: 22, name: "賽希", rarity: 5, class: "Caster", element: "Cryo", weapon: "Arts Unit", exclusiveWeapon: "", mainStat: "智識提升", subStat: "寒冷傷害提升", tags: ["輸出", "寒冷", "控制"], icon: "Xaihi_icon.png", fullImage: "Xaihi_Splash_Art.png", description: "穩健的卡西米亞冰霜術師，沉穩且實力強大。以輸出與控場兼具著稱，能在寒冷的戰場中穩定壓制敵人，為隊伍提供穩定火力。", gearRecommendation: { setName: "長息", pieces: ["長息裝甲", "長息護手壹型", "長息輔助臂", "長息輔助臂"] } },
     { id: 23, name: "伊馮", rarity: 6, class: "Striker", element: "Cryo", weapon: "Handcannon", exclusiveWeapon: "藝術暴君", mainStat: "智識提升", subStat: "暴擊率提升", tags: ["輸出", "寒冷", "爆擊"], icon: "Yvonne_icon.png", fullImage: "Yvonne_Splash_Art.png", description: "萊特寧公司旗下的頂級戰鬥術師，被稱為「藝術暴君」。具極高暴擊率，結合寒冷傷害形成壓制性輸出，常在戰場上掀起風暴。", gearRecommendation: { setName: "M.I.警用", pieces: ["M.I.警用罩衣", "脈衝式手套", "M.I.警用工具組", "M.I.警用工具組"] } }
 ];

window.operatorsData = operatorsData;
