/**
 * 武器數據
 */

const imageNameMap = {
    "塔爾11": "Tarr_11",
    "吉米尼12": "Jiminy_12",
    "佩科5": "Peco_5",
    "達爾霍夫7": "Darhoff_7",
    "奧佩羅77": "Opero_77",
    "應急手段": "Contingent_Measure",
    "浪潮": "Wave_Tide",
    "全自動駭新星": "Hypernova_Auto",
    "熒光雷羽": "Fluorescent_Roc",
    "呼嘯守衛": "Howling_Guard",
    "長路": "Long_Road",
    "工業零點一": "Industry_0.1",
    "淬火者": "Quencher",
    "鋼鐵餘音": "Sundering_Steel",
    "堅城鑄造者": "Fortmaker",
    "逐鱗3.0": "Finchaser_3.0",
    "十二問": "Twelve_Questions",
    "O.B.J.輕芒": "OBJ_Edge_of_Lightness",
    "仰止": "Aspirant",
    "悼亡詩": "Stanza_of_Memorials",
    "莫奈何": "Monaihe",
    "迷失荒野": "Wild_Wanderer",
    "布道自由": "Freedom_to_Proselytize",
    "O.B.J.術識": "OBJ_Arts_Identifier",
    "作品：眾生": "Opus_The_Living",
    "O.B.J.迅極": "OBJ_Velocitous",
    "理性告別": "Rational_Farewell",
    "作品：蝕跡": "Opus_Etch_Figure",
    "探驪": "Seeker_of_Dark_Lung",
    "古渠": "Ancient_Canal",
    "終點之聲": "Finishing_Call",
    "O.B.J.重荷": "OBJ_Heavy_Burden",
    "嵌合正義": "Chimeric_Justice",
    "O.B.J.尖峰": "OBJ_Razorhorn",
    "向心之引": "Cohesive_Traction",
    "宏願": "Grand_Vision",
    "不知歸": "Never_Rest",
    "熔鑄火焰": "Forgeborn_Scathe",
    "黯色火炬": "Umbral_Torch",
    "扶搖": "Rapid_Ascent",
    "熱熔切割器": "Thermite_Cutter",
    "顯赫聲明": "Eminent_Repute",
    "白夜新星": "White_Night_Nova",
    "使命必達": "Delivery_Guaranteed",
    "滄溟星夢": "Dreams_of_the_Starry_Beach",
    "爆破單元": "Detonation_Unit",
    "遺忘": "Oblivion",
    "騎士精神": "Chivalric_Virtues",
    "藝術暴君": "Artzy_Tyrannical",
    "領航者": "Navigator",
    "楔子": "Wedge",
    "同類相食": "Clannibal",
    "大雷斑": "Thunderberge",
    "赫拉芬格": "Khravengger",
    "典範": "Exemplar",
    "昔日精品": "Former_Finery",
    "破碎君王": "Sundered_Prince",
    "負山": "Mountain_Bearer",
    "驍勇": "Valiant",
    "J.E.T.": "JET",
    "導師者道標": "Pathfinder's_Beacon",
    "天使殺手": "Aggeloslayer"
};

const weaponsData = [
    { name: "塔爾11", wikiName: "Tarr_11", mainStat: "主能力提升", subStat: "/", skill: "強攻", rarity: "三星", type: "Sword", rarityNum: 3, tags: ["輸出", "物理"], exclusive: false },
    { name: "吉米尼12", wikiName: "Jiminy_12", mainStat: "主能力提升", subStat: "/", skill: "強攻", rarity: "三星", type: "Arts Unit", rarityNum: 3, tags: ["輸出", "法術"], exclusive: false },
    { name: "佩科5", wikiName: "Peco_5", mainStat: "主能力提升", subStat: "/", skill: "強攻", rarity: "三星", type: "Handcannon", rarityNum: 3, tags: ["輸出", "物理"], exclusive: false },
    { name: "達爾霍夫7", wikiName: "Darhoff_7", mainStat: "主能力提升", subStat: "/", skill: "強攻", rarity: "三星", type: "Greatsword", rarityNum: 3, tags: ["輸出", "範圍"], exclusive: false },
    { name: "奧佩羅77", wikiName: "Opero_77", mainStat: "主能力提升", subStat: "/", skill: "強攻", rarity: "三星", type: "Polearm", rarityNum: 3, tags: ["輸出", "穿刺"], exclusive: false },
    { name: "應急手段", wikiName: "Contingent_Measure", mainStat: "敏捷提升", subStat: "物理傷害提升", skill: "壓制", rarity: "四星", type: "Sword", rarityNum: 4, tags: ["輸出", "物理", "先手"], exclusive: false },
    { name: "浪潮", wikiName: "Wave_Tide", mainStat: "智識提升", subStat: "攻擊提升", skill: "追襲", rarity: "四星", type: "Sword", rarityNum: 4, tags: ["輸出", "法術", "追擊"], exclusive: false },
    { name: "全自動駭新星", wikiName: "Hypernova_Auto", mainStat: "智識提升", subStat: "法術提升", skill: "昂揚", rarity: "四星", type: "Arts Unit", rarityNum: 4, tags: ["輸出", "法術", "增傷"], exclusive: false },
    { name: "熒光雷羽", wikiName: "Fluorescent_Roc", mainStat: "意志提升", subStat: "攻擊提升", skill: "壓制", rarity: "四星", type: "Arts Unit", rarityNum: 4, tags: ["輸出", "法術", "雷電"], exclusive: false },
    { name: "呼嘯守衛", wikiName: "Howling_Guard", mainStat: "智識提升", subStat: "攻擊提升", skill: "壓制", rarity: "四星", type: "Handcannon", rarityNum: 4, tags: ["輸出", "物理", "壓制"], exclusive: false },
    { name: "長路", wikiName: "Long_Road", mainStat: "力量提升", subStat: "法術提升", skill: "追襲", rarity: "四星", type: "Handcannon", rarityNum: 4, tags: ["輸出", "法術", "追擊"], exclusive: false },
    { name: "工業零點一", wikiName: "Industry_0.1", mainStat: "力量提升", subStat: "攻擊提升", skill: "壓制", rarity: "四星", type: "Greatsword", rarityNum: 4, tags: ["輸出", "物理", "範圍"], exclusive: false },
    { name: "淬火者", wikiName: "Quencher", mainStat: "意志提升", subStat: "生命提升", skill: "粉碎", rarity: "四星", type: "Greatsword", rarityNum: 4, tags: ["防禦", "生命力", "反擊"], exclusive: false },
    { name: "導師者道標", wikiName: "Pathfinder's_Beacon", mainStat: "主能力提升", subStat: "攻擊提升", skill: "昂揚", rarity: "四星", type: "Polearm", rarityNum: 4, tags: ["輸出", "穿刺", "加速"], exclusive: false },
    { name: "天使殺手", wikiName: "Aggeloslayer", mainStat: "意志提升", subStat: "法術提升", skill: "壓制", rarity: "四星", type: "Polearm", rarityNum: 4, tags: ["輸出", "法術", "對天使"], exclusive: false },
    { name: "鋼鐵餘音", wikiName: "Sundering_Steel", mainStat: "敏捷提升", subStat: "物理傷害提升", skill: "巧技", rarity: "五星", type: "Sword", rarityNum: 5, tags: ["輸出", "物理", "爆擊"], exclusive: false },
    { name: "堅城鑄造者", wikiName: "Fortmaker", mainStat: "智識提升", subStat: "終結技充能效率提升", skill: "昂揚", rarity: "五星", type: "Sword", rarityNum: 5, tags: ["輔助", "法術", "終結技"], exclusive: false },
    { name: "逐鱗3.0", wikiName: "Finchaser_3.0", mainStat: "力量提升", subStat: "寒冷傷害提升", skill: "壓制", rarity: "五星", type: "Sword", rarityNum: 5, tags: ["輸出", "寒冷", "控制"], exclusive: false },
    { name: "十二問", wikiName: "Twelve_Questions", mainStat: "敏捷提升", subStat: "攻擊提升", skill: "附術", rarity: "五星", type: "Sword", rarityNum: 5, tags: ["輸出", "物理", "附加"], exclusive: false },
    { name: "O.B.J.輕芒", wikiName: "OBJ_Edge_of_Lightness", mainStat: "敏捷提升", subStat: "攻擊提升", skill: "流轉", rarity: "五星", type: "Sword", rarityNum: 5, tags: ["輸出", "物理", "流轉"], exclusive: false },
    { name: "仰止", wikiName: "Aspirant", mainStat: "敏捷提升", subStat: "物理傷害提升", skill: "夜幕", rarity: "五星", type: "Sword", rarityNum: 5, tags: ["輸出", "物理", "夜戰"], exclusive: false },
    { name: "悼亡詩", wikiName: "Stanza_of_Memorials", mainStat: "智識提升", subStat: "攻擊提升", skill: "夜幕", rarity: "五星", type: "Arts Unit", rarityNum: 5, tags: ["輸出", "法術", "夜戰"], exclusive: false },
    { name: "莫奈何", wikiName: "Monaihe", mainStat: "意志提升", subStat: "終結技充能效率提升", skill: "昂揚", rarity: "五星", type: "Arts Unit", rarityNum: 5, tags: ["輔助", "法術", "終結技"], exclusive: false },
    { name: "迷失荒野", wikiName: "Wild_Wanderer", mainStat: "智識提升", subStat: "電磁傷害提升", skill: "附術", rarity: "五星", type: "Arts Unit", rarityNum: 5, tags: ["輸出", "雷電", "附加"], exclusive: false },
    { name: "布道自由", wikiName: "Freedom_to_Proselytize", mainStat: "意志提升", subStat: "治療效率提升", skill: "醫療", rarity: "五星", type: "Arts Unit", rarityNum: 5, tags: ["輔助", "治療", "生命力"], exclusive: false },
    { name: "O.B.J.術識", wikiName: "OBJ_Arts_Identifier", mainStat: "智識提升", subStat: "源石技藝強度提升", skill: "追襲", rarity: "五星", type: "Arts Unit", rarityNum: 5, tags: ["輸出", "法術", "追擊"], exclusive: false },
    { name: "作品：眾生", wikiName: "Opus_The_Living", mainStat: "敏捷提升", subStat: "法術提升", skill: "附術", rarity: "五星", type: "Handcannon", rarityNum: 5, tags: ["輸出", "法術", "附加"], exclusive: false },
    { name: "O.B.J.迅極", wikiName: "OBJ_Velocitous", mainStat: "敏捷提升", subStat: "終結技充能效率提升", skill: "迸發", rarity: "五星", type: "Handcannon", rarityNum: 5, tags: ["輸出", "物理", "終結技"], exclusive: false },
    { name: "理性告別", wikiName: "Rational_Farewell", mainStat: "力量提升", subStat: "灼熱傷害提升", skill: "追襲", rarity: "五星", type: "Handcannon", rarityNum: 5, tags: ["輸出", "灼熱", "追擊"], exclusive: false },
    { name: "探驪", wikiName: "Seeker_of_Dark_Lung", mainStat: "力量提升", subStat: "終結技充能效率提升", skill: "迸發", rarity: "五星", type: "Greatsword", rarityNum: 5, tags: ["輸出", "範圍", "終結技"], exclusive: false },
    { name: "古渠", wikiName: "Ancient_Canal", mainStat: "力量提升", subStat: "源石技藝強度提升", skill: "殘暴", rarity: "五星", type: "Greatsword", rarityNum: 5, tags: ["輸出", "法術", "殘暴"], exclusive: false },
    { name: "終點之聲", wikiName: "Finishing_Call", mainStat: "力量提升", subStat: "生命提升", skill: "醫療", rarity: "五星", type: "Greatsword", rarityNum: 5, tags: ["防禦", "生命力", "治療"], exclusive: false },
    { name: "O.B.J.重荷", wikiName: "OBJ_Heavy_Burden", mainStat: "力量提升", subStat: "生命提升", skill: "效益", rarity: "五星", type: "Greatsword", rarityNum: 5, tags: ["防禦", "生命力", "效益"], exclusive: false },
    { name: "嵌合正義", wikiName: "Chimeric_Justice", mainStat: "力量提升", subStat: "終結技充能效率提升", skill: "殘暴", rarity: "五星", type: "Polearm", rarityNum: 5, tags: ["輸出", "穿刺", "終結技"], exclusive: false },
    { name: "O.B.J.尖峰", wikiName: "OBJ_Razorhorn", mainStat: "意志提升", subStat: "物理傷害提升", skill: "附術", rarity: "五星", type: "Polearm", rarityNum: 5, tags: ["輸出", "物理", "附加"], exclusive: false },
    { name: "向心之引", wikiName: "Cohesive_Traction", mainStat: "意志提升", subStat: "電磁傷害提升", skill: "壓制", rarity: "五星", type: "Polearm", rarityNum: 5, tags: ["輸出", "雷電", "控制"], exclusive: false },
    { name: "宏願", wikiName: "Grand_Vision", mainStat: "敏捷提升", subStat: "攻擊提升", skill: "附術", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "物理", "附加", "專武"], exclusive: true },
    { name: "不知歸", wikiName: "Never_Rest", mainStat: "意志提升", subStat: "攻擊提升", skill: "流轉", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "物理", "流轉", "專武"], exclusive: true },
    { name: "熔鑄火焰", wikiName: "Forgeborn_Scathe", mainStat: "智識提升", subStat: "攻擊提升", skill: "夜幕", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "灼熱", "夜戰", "專武"], exclusive: true },
    { name: "黯色火炬", wikiName: "Umbral_Torch", mainStat: "智識提升", subStat: "灼熱傷害提升", skill: "附術", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "灼熱", "附加"], exclusive: false },
    { name: "扶搖", wikiName: "Khravengger", mainStat: "主能力提升", subStat: "暴擊率提升", skill: "夜幕", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "物理", "爆擊", "夜戰"], exclusive: false },
    { name: "熱熔切割器", wikiName: "Thermite_Cutter", mainStat: "意志提升", subStat: "攻擊提升", skill: "流轉", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "物理", "流轉"], exclusive: false },
    { name: "顯赫聲明", wikiName: "Eminent_Repute", mainStat: "主能力提升", subStat: "物理傷害提升", skill: "殘暴", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "物理", "殘暴"], exclusive: false },
    { name: "白夜新星", wikiName: "White_Night_Nova", mainStat: "主能力提升", subStat: "源石技藝強度提升", skill: "附術", rarity: "六星", type: "Sword", rarityNum: 6, tags: ["輸出", "法術", "附加"], exclusive: false },
    { name: "使命必達", wikiName: "Delivery_Guaranteed", mainStat: "意志提升", subStat: "終結技充能效率提升", skill: "追襲", rarity: "六星", type: "Arts Unit", rarityNum: 6, tags: ["輔助", "治療", "追擊", "專武"], exclusive: true },
    { name: "滄溟星夢", wikiName: "Dreams_of_the_Starry_Beach", mainStat: "智識提升", subStat: "治療效率提升", skill: "附術", rarity: "六星", type: "Arts Unit", rarityNum: 6, tags: ["輔助", "治療", "護盾", "專武"], exclusive: true },
    { name: "作品：蝕跡", wikiName: "Opus_Etch_Figure", mainStat: "意志提升", subStat: "自然傷害提升", skill: "壓制", rarity: "六星", type: "Arts Unit", rarityNum: 6, tags: ["輸出", "自然", "控制"], exclusive: false },
    { name: "爆破單元", wikiName: "Detonation_Unit", mainStat: "主能力提升", subStat: "源石技藝強度提升", skill: "迸發", rarity: "六星", type: "Arts Unit", rarityNum: 6, tags: ["輸出", "法術", "爆發"], exclusive: false },
    { name: "遺忘", wikiName: "Oblivion", mainStat: "智識提升", subStat: "法術提升", skill: "夜幕", rarity: "六星", type: "Arts Unit", rarityNum: 6, tags: ["輸出", "法術", "夜戰"], exclusive: false },
    { name: "騎士精神", wikiName: "Chivalric_Virtues", mainStat: "意志提升", subStat: "生命提升", skill: "醫療", rarity: "六星", type: "Arts Unit", rarityNum: 6, tags: ["輔助", "治療", "生命力"], exclusive: false },
    { name: "藝術暴君", wikiName: "Artzy_Tyrannical", mainStat: "智識提升", subStat: "暴擊率提升", skill: "切骨", rarity: "六星", type: "Handcannon", rarityNum: 6, tags: ["輸出", "物理", "爆擊", "專武"], exclusive: true },
    { name: "領航者", wikiName: "Navigator", mainStat: "智識提升", subStat: "寒冷傷害提升", skill: "附術", rarity: "六星", type: "Handcannon", rarityNum: 6, tags: ["輸出", "寒冷", "附加"], exclusive: false },
    { name: "楔子", wikiName: "Wedge", mainStat: "主能力提升", subStat: "暴擊率提升", skill: "附術", rarity: "六星", type: "Handcannon", rarityNum: 6, tags: ["輸出", "物理", "爆擊"], exclusive: false },
    { name: "同類相食", wikiName: "Clannibal", mainStat: "主能力提升", subStat: "法術提升", skill: "附術", rarity: "六星", type: "Handcannon", rarityNum: 6, tags: ["輸出", "法術", "附加"], exclusive: false },
    { name: "大雷斑", wikiName: "Thunderberge", mainStat: "力量提升", subStat: "生命提升", skill: "醫療", rarity: "六星", type: "Greatsword", rarityNum: 6, tags: ["防禦", "生命力", "治療", "專武"], exclusive: true },
    { name: "赫拉芬格", wikiName: "Khravengger", mainStat: "力量提升", subStat: "攻擊提升", skill: "迸發", rarity: "六星", type: "Greatsword", rarityNum: 6, tags: ["輸出", "範圍", "爆發", "專武"], exclusive: true },
    { name: "典範", wikiName: "Exemplar", mainStat: "主能力提升", subStat: "攻擊提升", skill: "壓制", rarity: "六星", type: "Greatsword", rarityNum: 6, tags: ["輸出", "物理", "壓制"], exclusive: false },
    { name: "昔日精品", wikiName: "Former_Finery", mainStat: "意志提升", subStat: "生命提升", skill: "效益", rarity: "六星", type: "Greatsword", rarityNum: 6, tags: ["防禦", "生命力", "效益"], exclusive: false },
    { name: "破碎君王", wikiName: "Sundered_Prince", mainStat: "力量提升", subStat: "暴擊率提升", skill: "粉碎", rarity: "六星", type: "Greatsword", rarityNum: 6, tags: ["輸出", "物理", "爆擊"], exclusive: false },
    { name: "負山", wikiName: "Mountain_Bearer", mainStat: "敏捷提升", subStat: "物理傷害提升", skill: "效益", rarity: "六星", type: "Polearm", rarityNum: 6, tags: ["防禦", "保護", "效益", "專武"], exclusive: true },
    { name: "驍勇", wikiName: "Valiant", mainStat: "敏捷提升", subStat: "物理傷害提升", skill: "巧技", rarity: "六星", type: "Polearm", rarityNum: 6, tags: ["輸出", "物理", "技巧"], exclusive: false },
    { name: "J.E.T.", wikiName: "JET", mainStat: "主能力提升", subStat: "攻擊提升", skill: "壓制", rarity: "六星", type: "Polearm", rarityNum: 6, tags: ["輸出", "物理", "壓制"], exclusive: false }
];

function getWeaponImageUrl(weapon) {
    const wikiName = weapon.wikiName || weapon.name;
    return `images/${wikiName}.png`;
}

window.weaponsData = weaponsData;
window.imageNameMap = imageNameMap;
window.getWeaponImageUrl = getWeaponImageUrl;
